# Generated by Django 4.2.4 on 2023-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_article_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
