# Generated by Django 4.2.4 on 2023-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_document_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
