# Generated by Django 4.2.4 on 2023-09-04 03:16

from django.db import migrations, models
import social.models.observable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('MATH', 'MATH'), ('PHYSICS', 'PHYSICS'), ('CALCULUS', 'CALCULUS'), ('PROGRAMMING', 'PROGRAMMING'), ('LITERATURE', 'LITERATURE'), ('ECONOMY', 'ECONOMY'), ('GEOMETRY', 'GEOMETRY'), ('CHEMISTRY', 'CHEMISTRY')], default='UNKNOWN', max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            bases=(models.Model, social.models.observable.Observable),
        ),
    ]
