CAN_NOTE_PERMISSION = 'CanNote'
CAN_READ_PERMISSION = 'CanRead'
CAN_CREATE_COLLECTION_PERMISSION = 'CanCreateCollection'
CAN_PUBLISH_PERMISSION = 'CanPublish'

READER_GROUP = 'Reader'
PROFESSOR_GROUP = 'Professor'
